In [1]:
import pandas as pd

# 1. Создание

### 1.1 Создаём дата-фрейм на основе CSV

In [173]:
# создание объекта DataFrame на основе CSV-файла
df = pd.read_csv("gym_churn.csv")
df

,gender,Near_Location,Partner,Promo_friends,Phone,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn
0,1,1,1,1,0,6,1,29,14.227470,5.0,3,0.020398,0.000000,0
1,0,1,0,0,1,12,1,31,113.202938,12.0,7,1.922936,1.910244,0
2,0,1,1,0,1,1,0,28,129.448479,1.0,2,1.859098,1.736502,0
3,0,1,1,1,1,12,1,33,62.669863,12.0,2,3.205633,3.357215,0
4,1,1,1,1,1,1,0,26,198.362265,1.0,3,1.113884,1.120078,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,1,1,1,0,1,12,0,33,2.406023,12.0,8,2.284497,2.349070,0
3996,0,1,0,0,1,1,1,29,68.883764,1.0,1,1.277168,0.292859,1
3997,1,1,1,1,1,12,0,28,78.250542,11.0,2,2.786146,2.831439,0
3998,0,1,1,1,1,6,0,32,61.912657,5.0,3,1.630108,1.596237,0
3999,1,0,1,0,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0

In [39]:
df.head() # вывод первых 5 строк

,gender,Near_Location,Partner,Promo_friends,Phone,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn
0,1,1,1,1,0,6,1,29,14.227470,5.0,3,0.020398,0.000000,0
1,0,1,0,0,1,12,1,31,113.202938,12.0,7,1.922936,1.910244,0
2,0,1,1,0,1,1,0,28,129.448479,1.0,2,1.859098,1.736502,0
3,0,1,1,1,1,12,1,33,62.669863,12.0,2,3.205633,3.357215,0
4,1,1,1,1,1,1,0,26,198.362265,1.0,3,1.113884,1.120078,0

In [41]:
len(df) # сколько строк данных?

4000

### 1.2 Создаём на основе словаря

In [6]:
tempdict = {'col1':[1,2,3], 'col2':[4,5,6], 'col3':[7,8,9]}

In [174]:
dd = pd.DataFrame.from_dict(tempdict)
dd

   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9

In [43]:
dd = pd.DataFrame(tempdict)
dd

   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9

# 2. Чтение

### 2.1 Смотрим первые и последние 5 строк

In [44]:
df.head()

,gender,Near_Location,Partner,Promo_friends,Phone,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn
0,1,1,1,1,0,6,1,29,14.227470,5.0,3,0.020398,0.000000,0
1,0,1,0,0,1,12,1,31,113.202938,12.0,7,1.922936,1.910244,0
2,0,1,1,0,1,1,0,28,129.448479,1.0,2,1.859098,1.736502,0
3,0,1,1,1,1,12,1,33,62.669863,12.0,2,3.205633,3.357215,0
4,1,1,1,1,1,1,0,26,198.362265,1.0,3,1.113884,1.120078,0

In [175]:
dd.head(2)

   col1  col2  col3
0     1     4     7
1     2     5     8

In [46]:
df.tail()

,gender,Near_Location,Partner,Promo_friends,Phone,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn
3995,1,1,1,0,1,12,0,33,2.406023,12.0,8,2.284497,2.349070,0
3996,0,1,0,0,1,1,1,29,68.883764,1.0,1,1.277168,0.292859,1
3997,1,1,1,1,1,12,0,28,78.250542,11.0,2,2.786146,2.831439,0
3998,0,1,1,1,1,6,0,32,61.912657,5.0,3,1.630108,1.596237,0
3999,1,0,1,0,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0

In [64]:
df.tail(15) # выводим последние 15 строк

,gender,Near_Location,Partner,Promo_friends,Phone,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn
3985,0,1,1,1,1,12,1,29,13.328843,9.0,2,2.186940,2.351317,0
3986,0,1,1,1,1,1,1,34,226.804845,1.0,0,1.399529,0.304130,1
3987,1,1,1,0,1,6,0,33,113.383421,6.0,8,3.620360,3.434806,0
3988,0,1,0,0,1,12,1,25,33.118529,12.0,2,0.798169,0.955526,0
3989,0,1,1,0,1,6,1,30,172.683294,5.0,6,2.225015,2.267794,0
3990,1,0,1,0,1,12,0,33,31.771147,8.0,10,1.831577,1.924509,0
3991,1,0,1,0,1,6,0,33,69.301270,6.0,1,1.367289,1.435721,0
3992,0,1,1,1,1,12,0,31,223.102448,8.0,4,3.855916,3.797062,0
3993,0,1,1,0,1,1,0,33,231.778628,1.0,3,1.418791,1.450442,0
3994,1,1,0,0,1,1,0,26,31.066721,1.0,1,1.157451,0.269597,1
3995,1,1,1,0,1,12,0,33,2.406023,12.0,8,2.284497,2.349070,0
3996,0,1,0,0,1,1,1,29,68.883764,1.0,1,1.277168,0.292859,1
3997,1,1,1,1,1,12,0,28,78.250542,11.0,2,2.786146,2.831439,0
3998,0,1,1,1,1,6,0,32,61.912657,5.0,3,1.630108,1.596237,0
3999,1,0,1,0,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0

### 2.2 Просмотр столбцов и типов данных

In [53]:
df.columns # получаем имена столбцов

Index(['gender', 'Near_Location', 'Partner', 'Promo_friends', 'Phone',
       'Contract_period', 'Group_visits', 'Age',
       'Avg_additional_charges_total', 'Month_to_end_contract', 'Lifetime',
       'Avg_class_frequency_total', 'Avg_class_frequency_current_month',
       'Churn'],
      dtype='object')

In [57]:
df.dtypes # смотрим типы столбцов

gender                                 int64
Near_Location                          int64
Partner                                int64
Promo_friends                          int64
Phone                                  int64
Contract_period                        int64
Group_visits                           int64
Age                                    int64
Avg_additional_charges_total         float64
Month_to_end_contract                float64
Lifetime                               int64
Avg_class_frequency_total            float64
Avg_class_frequency_current_month    float64
Churn                                  int64
dtype: object

### 2.3 Статистика

In [58]:
df.describe() # получаем статистические данные по каждому столбцу

,gender,Near_Location,Partner,Promo_friends,Phone,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,0.510250,0.845250,0.486750,0.308500,0.903500,4.681250,0.412250,29.184250,146.943728,4.322750,3.724750,1.879020,1.767052,0.265250
std,0.499957,0.361711,0.499887,0.461932,0.295313,4.549706,0.492301,3.258367,96.355602,4.191297,3.749267,0.972245,1.052906,0.441521
min,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,18.000000,0.148205,1.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,27.000000,68.868830,1.000000,1.000000,1.180875,0.963003,0.000000
50%,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,29.000000,136.220159,1.000000,3.000000,1.832768,1.719574,0.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,1.000000,31.000000,210.949625,6.000000,5.000000,2.536078,2.510336,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,12.000000,1.000000,41.000000,552.590740,12.000000,31.000000,6.023668,6.146783,1.000000

In [68]:
df.describe(include="float64")

,Avg_additional_charges_total,Month_to_end_contract,Avg_class_frequency_total,Avg_class_frequency_current_month
count,4000.000000,4000.000000,4000.000000,4000.000000
mean,146.943728,4.322750,1.879020,1.767052
std,96.355602,4.191297,0.972245,1.052906
min,0.148205,1.000000,0.000000,0.000000
25%,68.868830,1.000000,1.180875,0.963003
50%,136.220159,1.000000,1.832768,1.719574
75%,210.949625,6.000000,2.536078,2.510336
max,552.590740,12.000000,6.023668,6.146783

### 2.4 Фильтрация столбцов

In [62]:
df["gender"] # выводим только 1 столбец gender

0       1
1       0
2       0
3       0
4       1
       ..
3995    1
3996    0
3997    1
3998    0
3999    1
Name: gender, Length: 4000, dtype: int64

In [63]:
df.gender # альтернативный метод просмотра нужного столбца

0       1
1       0
2       0
3       0
4       1
       ..
3995    1
3996    0
3997    1
3998    0
3999    1
Name: gender, Length: 4000, dtype: int64

In [69]:
df["Churn"]

0       0
1       0
2       0
3       0
4       0
       ..
3995    0
3996    1
3997    0
3998    0
3999    0
Name: Churn, Length: 4000, dtype: int64

In [70]:
df[["gender", "Age"]]# просмотр нескольких столбцов

      gender  Age
0          1   29
1          0   31
2          0   28
3          0   33
4          1   26
...      ...  ...
3995       1   33
3996       0   29
3997       1   28
3998       0   32
3999       1   30

[4000 rows x 2 columns]

In [72]:
df.gender.unique() # список уникальных значений в столбце gender

array([1, 0])

In [73]:
df["gender"].unique()

array([1, 0])

In [74]:
df.Age.unique()

array([29, 31, 28, 33, 26, 34, 32, 30, 23, 27, 35, 25, 36, 24, 21, 37, 22,
       19, 20, 38, 39, 18, 41])

### 2.5 Фильтрация по значениям

In [75]:
df

,gender,Near_Location,Partner,Promo_friends,Phone,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn
0,1,1,1,1,0,6,1,29,14.227470,5.0,3,0.020398,0.000000,0
1,0,1,0,0,1,12,1,31,113.202938,12.0,7,1.922936,1.910244,0
2,0,1,1,0,1,1,0,28,129.448479,1.0,2,1.859098,1.736502,0
3,0,1,1,1,1,12,1,33,62.669863,12.0,2,3.205633,3.357215,0
4,1,1,1,1,1,1,0,26,198.362265,1.0,3,1.113884,1.120078,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,1,1,1,0,1,12,0,33,2.406023,12.0,8,2.284497,2.349070,0
3996,0,1,0,0,1,1,1,29,68.883764,1.0,1,1.277168,0.292859,1
3997,1,1,1,1,1,12,0,28,78.250542,11.0,2,2.786146,2.831439,0
3998,0,1,1,1,1,6,0,32,61.912657,5.0,3,1.630108,1.596237,0
3999,1,0,1,0,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0

In [83]:
df[df["Near_Location"]==0] # оставляем только те ячейки, у которых "Near_Location" == "No"

,gender,Near_Location,Partner,Promo_friends,Phone,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn
21,0,0,0,0,1,1,0,30,153.198594,1.0,3,0.636382,0.000000,1
25,0,0,0,0,1,1,0,29,57.730007,1.0,0,1.491187,1.246807,1
51,1,0,1,0,1,1,0,29,373.066503,1.0,0,1.685823,1.661742,0
75,1,0,0,0,1,1,0,30,8.398417,1.0,2,1.851313,1.363330,1
76,1,0,0,0,1,1,1,30,249.513088,1.0,2,0.875440,1.002299,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3962,1,0,1,1,1,1,0,29,224.099662,1.0,8,2.539546,2.653997,0
3974,0,0,0,0,1,1,0,28,123.869410,1.0,2,0.498446,0.371811,1
3990,1,0,1,0,1,12,0,33,31.771147,8.0,10,1.831577,1.924509,0
3991,1,0,1,0,1,6,0,33,69.301270,6.0,1,1.367289,1.435721,0
3999,1,0,1,0,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0

In [87]:
df[(df["gender"] == 1) & (df["Age"] > 29)]# несколько условий фильтрации

,gender,Near_Location,Partner,Promo_friends,Phone,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn
5,1,1,0,0,1,1,1,34,450.743960,1.0,3,2.623477,2.637007,0
6,1,1,1,1,0,6,1,32,94.266389,6.0,2,1.138941,1.277242,0
23,1,1,0,0,1,1,1,32,276.079882,1.0,1,1.420637,1.043101,1
37,1,1,0,0,1,1,1,32,14.254721,1.0,21,3.372314,3.315715,0
39,1,1,0,1,0,6,1,35,233.239548,6.0,0,1.270752,1.206591,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3987,1,1,1,0,1,6,0,33,113.383421,6.0,8,3.620360,3.434806,0
3990,1,0,1,0,1,12,0,33,31.771147,8.0,10,1.831577,1.924509,0
3991,1,0,1,0,1,6,0,33,69.301270,6.0,1,1.367289,1.435721,0
3995,1,1,1,0,1,12,0,33,2.406023,12.0,8,2.284497,2.349070,0
3999,1,0,1,0,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0

### 2.6 Выводим строки при помощи .iloc

In [88]:
df.iloc[14]# выводим 14 строку

gender                                 0.000000
Near_Location                          1.000000
Partner                                0.000000
Promo_friends                          0.000000
Phone                                  1.000000
Contract_period                        6.000000
Group_visits                           0.000000
Age                                   35.000000
Avg_additional_charges_total         209.888133
Month_to_end_contract                  3.000000
Lifetime                               8.000000
Avg_class_frequency_total              1.978084
Avg_class_frequency_current_month      2.117349
Churn                                  0.000000
Name: 14, dtype: float64

In [92]:
df.iloc[14,-1]# выводим последнюю ячейку 14 строки

np.int64(0)

In [93]:
df.iloc[22:33]# выводим строки 22-32

,gender,Near_Location,Partner,Promo_friends,Phone,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn
22,1,1,0,0,1,12,1,29,100.158130,12.0,1,3.899715,3.709855,0
23,1,1,0,0,1,1,1,32,276.079882,1.0,1,1.420637,1.043101,1
24,0,1,0,1,0,6,0,27,179.555457,6.0,6,3.393161,3.282515,0
25,0,0,0,0,1,1,0,29,57.730007,1.0,0,1.491187,1.246807,1
26,0,1,1,0,1,6,0,29,167.875211,6.0,5,3.311350,3.243412,0
27,1,1,0,1,1,6,0,27,31.805390,6.0,3,0.824283,0.795761,0
28,0,1,0,0,1,1,0,28,242.366501,1.0,15,1.459409,1.320372,0
29,0,1,1,1,1,6,1,27,159.148924,5.0,3,3.511568,3.528886,0
30,0,1,1,0,1,1,1,32,44.672508,1.0,1,1.771692,1.687872,0
31,0,1,0,0,1,12,1,32,87.856139,12.0,1,0.000000,0.000000,0
32,0,1,0,0,1,12,0,32,131.114586,12.0,3,2.374935,2.265089,0

### 2.7 Выводим нужные строки при помощи .loc

In [107]:
dfc = df.copy()
dfc # копируем дата-фрейм

,gender,Near_Location,Partner,Promo_friends,Phone,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn
0,1,1,1,1,0,6,1,29,14.227470,5.0,3,0.020398,0.000000,0
1,0,1,0,0,1,12,1,31,113.202938,12.0,7,1.922936,1.910244,0
2,0,1,1,0,1,1,0,28,129.448479,1.0,2,1.859098,1.736502,0
3,0,1,1,1,1,12,1,33,62.669863,12.0,2,3.205633,3.357215,0
4,1,1,1,1,1,1,0,26,198.362265,1.0,3,1.113884,1.120078,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,1,1,1,0,1,12,0,33,2.406023,12.0,8,2.284497,2.349070,0
3996,0,1,0,0,1,1,1,29,68.883764,1.0,1,1.277168,0.292859,1
3997,1,1,1,1,1,12,0,28,78.250542,11.0,2,2.786146,2.831439,0
3998,0,1,1,1,1,6,0,32,61.912657,5.0,3,1.630108,1.596237,0
3999,1,0,1,0,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0

In [108]:
dfc.set_index("Contract_period", inplace=True)
dfc

,gender,Near_Location,Partner,Promo_friends,Phone,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn
Contract_period,,,,,,,,,,,,,
6,1,1,1,1,0,1,29,14.227470,5.0,3,0.020398,0.000000,0
12,0,1,0,0,1,1,31,113.202938,12.0,7,1.922936,1.910244,0
1,0,1,1,0,1,0,28,129.448479,1.0,2,1.859098,1.736502,0
12,0,1,1,1,1,1,33,62.669863,12.0,2,3.205633,3.357215,0
1,1,1,1,1,1,0,26,198.362265,1.0,3,1.113884,1.120078,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12,1,1,1,0,1,0,33,2.406023,12.0,8,2.284497,2.349070,0
1,0,1,0,0,1,1,29,68.883764,1.0,1,1.277168,0.292859,1
12,1,1,1,1,1,0,28,78.250542,11.0,2,2.786146,2.831439,0
6,0,1,1,1,1,0,32,61.912657,5.0,3,1.630108,1.596237,0
12,1,0,1,0,0,1,30,178.861814,12.0,1,1.101832,1.035270,0

In [111]:
dfc.loc[6] # выводим все строки, где Contract_period == 6

,gender,Near_Location,Partner,Promo_friends,Phone,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn
Contract_period,,,,,,,,,,,,,
6,1,1,1,1,0,1,29,14.227470,5.0,3,0.020398,0.000000,0
6,1,1,1,1,0,1,32,94.266389,6.0,2,1.138941,1.277242,0
6,0,1,0,0,0,1,32,229.708945,6.0,3,1.641180,1.367714,0
6,0,1,0,0,1,0,35,209.888133,3.0,8,1.978084,2.117349,0
6,0,1,0,1,1,1,29,92.787414,5.0,1,0.664482,0.609945,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,1,1,0,0,1,1,22,101.107544,6.0,2,1.377860,0.343915,1
6,1,1,1,0,1,0,33,113.383421,6.0,8,3.620360,3.434806,0
6,0,1,1,0,1,1,30,172.683294,5.0,6,2.225015,2.267794,0
6,1,0,1,0,1,0,33,69.301270,6.0,1,1.367289,1.435721,0
6,0,1,1,1,1,0,32,61.912657,5.0,3,1.630108,1.596237,0

# 3. Изменяем дата-фрейм

### 3.1 Удаляем данные

In [187]:
df.isnull() # поиск значений NaN

,gender,Near_Location,Partner,Promo_friends,Phone,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3997,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3998,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [188]:
df["New"] = df["Month_to_end_contract"]-df["Lifetime"]

In [189]:
df

,gender,Near_Location,Partner,Promo_friends,Phone,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn,New
0,1,1,1,1,0,6,1,29,14.227470,5.0,3,0.020398,0.000000,0,2.0
1,0,1,0,0,1,12,1,31,113.202938,12.0,7,1.922936,1.910244,0,5.0
2,0,1,1,0,1,1,0,28,129.448479,1.0,2,1.859098,1.736502,0,-1.0
3,0,1,1,1,1,12,1,33,62.669863,12.0,2,3.205633,3.357215,0,10.0
4,1,1,1,1,1,1,0,26,198.362265,1.0,3,1.113884,1.120078,0,-2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,1,1,1,0,1,12,0,33,2.406023,12.0,8,2.284497,2.349070,0,4.0
3996,0,1,0,0,1,1,1,29,68.883764,1.0,1,1.277168,0.292859,1,0.0
3997,1,1,1,1,1,12,0,28,78.250542,11.0,2,2.786146,2.831439,0,9.0
3998,0,1,1,1,1,6,0,32,61.912657,5.0,3,1.630108,1.596237,0,2.0
3999,1,0,1,0,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0,11.0

In [190]:
df.loc[df["New"] < 0, "New"] = None
df

,gender,Near_Location,Partner,Promo_friends,Phone,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn,New
0,1,1,1,1,0,6,1,29,14.227470,5.0,3,0.020398,0.000000,0,2.0
1,0,1,0,0,1,12,1,31,113.202938,12.0,7,1.922936,1.910244,0,5.0
2,0,1,1,0,1,1,0,28,129.448479,1.0,2,1.859098,1.736502,0,NaN
3,0,1,1,1,1,12,1,33,62.669863,12.0,2,3.205633,3.357215,0,10.0
4,1,1,1,1,1,1,0,26,198.362265,1.0,3,1.113884,1.120078,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,1,1,1,0,1,12,0,33,2.406023,12.0,8,2.284497,2.349070,0,4.0
3996,0,1,0,0,1,1,1,29,68.883764,1.0,1,1.277168,0.292859,1,0.0
3997,1,1,1,1,1,12,0,28,78.250542,11.0,2,2.786146,2.831439,0,9.0
3998,0,1,1,1,1,6,0,32,61.912657,5.0,3,1.630108,1.596237,0,2.0
3999,1,0,1,0,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0,11.0

In [191]:
df.isnull().sum() # суммируем все найденные значения NaN

gender                                  0
Near_Location                           0
Partner                                 0
Promo_friends                           0
Phone                                   0
Contract_period                         0
Group_visits                            0
Age                                     0
Avg_additional_charges_total            0
Month_to_end_contract                   0
Lifetime                                0
Avg_class_frequency_total               0
Avg_class_frequency_current_month       0
Churn                                   0
New                                  1520
dtype: int64

In [192]:
df.dropna()
df # .dropna удаляем пропущенные значения в серии

,gender,Near_Location,Partner,Promo_friends,Phone,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn,New
0,1,1,1,1,0,6,1,29,14.227470,5.0,3,0.020398,0.000000,0,2.0
1,0,1,0,0,1,12,1,31,113.202938,12.0,7,1.922936,1.910244,0,5.0
2,0,1,1,0,1,1,0,28,129.448479,1.0,2,1.859098,1.736502,0,NaN
3,0,1,1,1,1,12,1,33,62.669863,12.0,2,3.205633,3.357215,0,10.0
4,1,1,1,1,1,1,0,26,198.362265,1.0,3,1.113884,1.120078,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,1,1,1,0,1,12,0,33,2.406023,12.0,8,2.284497,2.349070,0,4.0
3996,0,1,0,0,1,1,1,29,68.883764,1.0,1,1.277168,0.292859,1,0.0
3997,1,1,1,1,1,12,0,28,78.250542,11.0,2,2.786146,2.831439,0,9.0
3998,0,1,1,1,1,6,0,32,61.912657,5.0,3,1.630108,1.596237,0,2.0
3999,1,0,1,0,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0,11.0

In [193]:
df.isna().sum()

gender                                  0
Near_Location                           0
Partner                                 0
Promo_friends                           0
Phone                                   0
Contract_period                         0
Group_visits                            0
Age                                     0
Avg_additional_charges_total            0
Month_to_end_contract                   0
Lifetime                                0
Avg_class_frequency_total               0
Avg_class_frequency_current_month       0
Churn                                   0
New                                  1520
dtype: int64

In [194]:
df = pd.read_csv("gym_churn.csv")
df["New"] = df["Month_to_end_contract"]-df["Lifetime"]
df.loc[df["New"] < 0, "New"] = None
df

,gender,Near_Location,Partner,Promo_friends,Phone,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn,New
0,1,1,1,1,0,6,1,29,14.227470,5.0,3,0.020398,0.000000,0,2.0
1,0,1,0,0,1,12,1,31,113.202938,12.0,7,1.922936,1.910244,0,5.0
2,0,1,1,0,1,1,0,28,129.448479,1.0,2,1.859098,1.736502,0,NaN
3,0,1,1,1,1,12,1,33,62.669863,12.0,2,3.205633,3.357215,0,10.0
4,1,1,1,1,1,1,0,26,198.362265,1.0,3,1.113884,1.120078,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,1,1,1,0,1,12,0,33,2.406023,12.0,8,2.284497,2.349070,0,4.0
3996,0,1,0,0,1,1,1,29,68.883764,1.0,1,1.277168,0.292859,1,0.0
3997,1,1,1,1,1,12,0,28,78.250542,11.0,2,2.786146,2.831439,0,9.0
3998,0,1,1,1,1,6,0,32,61.912657,5.0,3,1.630108,1.596237,0,2.0
3999,1,0,1,0,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0,11.0

In [196]:
df["New"] = df["Month_to_end_contract"]-df["Lifetime"]
df.loc[df["New"] < 0, "New"] = None
df.dropna(inplace=True)
df

,gender,Near_Location,Partner,Promo_friends,Phone,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn,New
0,1,1,1,1,0,6,1,29,14.227470,5.0,3,0.020398,0.000000,0,2.0
1,0,1,0,0,1,12,1,31,113.202938,12.0,7,1.922936,1.910244,0,5.0
3,0,1,1,1,1,12,1,33,62.669863,12.0,2,3.205633,3.357215,0,10.0
6,1,1,1,1,0,6,1,32,94.266389,6.0,2,1.138941,1.277242,0,4.0
7,0,1,0,0,1,1,0,30,217.786641,1.0,0,1.213502,1.049387,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,1,1,1,0,1,12,0,33,2.406023,12.0,8,2.284497,2.349070,0,4.0
3996,0,1,0,0,1,1,1,29,68.883764,1.0,1,1.277168,0.292859,1,0.0
3997,1,1,1,1,1,12,0,28,78.250542,11.0,2,2.786146,2.831439,0,9.0
3998,0,1,1,1,1,6,0,32,61.912657,5.0,3,1.630108,1.596237,0,2.0
3999,1,0,1,0,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0,11.0

### 3.2 Удаляем столбцы

In [134]:
df.drop('Phone', axis=1) # удаляем столбец "Area code"
df

,gender,Near_Location,Partner,Promo_friends,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn
0,1,1,1,1,6,1,29,14.227470,5.0,3,0.020398,0.000000,0
1,0,1,0,0,12,1,31,113.202938,12.0,7,1.922936,1.910244,0
2,0,1,1,0,1,0,28,129.448479,1.0,2,1.859098,1.736502,0
3,0,1,1,1,12,1,33,62.669863,12.0,2,3.205633,3.357215,0
4,1,1,1,1,1,0,26,198.362265,1.0,3,1.113884,1.120078,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,1,1,1,0,12,0,33,2.406023,12.0,8,2.284497,2.349070,0
3996,0,1,0,0,1,1,29,68.883764,1.0,1,1.277168,0.292859,1
3997,1,1,1,1,12,0,28,78.250542,11.0,2,2.786146,2.831439,0
3998,0,1,1,1,6,0,32,61.912657,5.0,3,1.630108,1.596237,0
3999,1,0,1,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0

### 3.3 Создание столбца с суммой других столбцов

In [136]:
df["Sum of Avgs"] = df["Avg_additional_charges_total"] + df["Avg_class_frequency_total"] # запись в столбец суммы других столбцов

In [137]:
df

,gender,Near_Location,Partner,Promo_friends,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn,Sum of Avgs
0,1,1,1,1,6,1,29,14.227470,5.0,3,0.020398,0.000000,0,14.247868
1,0,1,0,0,12,1,31,113.202938,12.0,7,1.922936,1.910244,0,115.125874
2,0,1,1,0,1,0,28,129.448479,1.0,2,1.859098,1.736502,0,131.307578
3,0,1,1,1,12,1,33,62.669863,12.0,2,3.205633,3.357215,0,65.875496
4,1,1,1,1,1,0,26,198.362265,1.0,3,1.113884,1.120078,0,199.476150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,1,1,1,0,12,0,33,2.406023,12.0,8,2.284497,2.349070,0,4.690520
3996,0,1,0,0,1,1,29,68.883764,1.0,1,1.277168,0.292859,1,70.160932
3997,1,1,1,1,12,0,28,78.250542,11.0,2,2.786146,2.831439,0,81.036688
3998,0,1,1,1,6,0,32,61.912657,5.0,3,1.630108,1.596237,0,63.542765
3999,1,0,1,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0,179.963646

### 3.4 Заполнение столбца данными

In [138]:
df["Sum of Avgs"] = 100 # заполнение столбца 100
df

,gender,Near_Location,Partner,Promo_friends,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn,Sum of Avgs
0,1,1,1,1,6,1,29,14.227470,5.0,3,0.020398,0.000000,0,100
1,0,1,0,0,12,1,31,113.202938,12.0,7,1.922936,1.910244,0,100
2,0,1,1,0,1,0,28,129.448479,1.0,2,1.859098,1.736502,0,100
3,0,1,1,1,12,1,33,62.669863,12.0,2,3.205633,3.357215,0,100
4,1,1,1,1,1,0,26,198.362265,1.0,3,1.113884,1.120078,0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,1,1,1,0,12,0,33,2.406023,12.0,8,2.284497,2.349070,0,100
3996,0,1,0,0,1,1,29,68.883764,1.0,1,1.277168,0.292859,1,100
3997,1,1,1,1,12,0,28,78.250542,11.0,2,2.786146,2.831439,0,100
3998,0,1,1,1,6,0,32,61.912657,5.0,3,1.630108,1.596237,0,100
3999,1,0,1,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0,100

In [139]:
df.loc[df["gender"] == 1, "Sum of Avgs"] = 200
df

,gender,Near_Location,Partner,Promo_friends,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn,Sum of Avgs
0,1,1,1,1,6,1,29,14.227470,5.0,3,0.020398,0.000000,0,200
1,0,1,0,0,12,1,31,113.202938,12.0,7,1.922936,1.910244,0,100
2,0,1,1,0,1,0,28,129.448479,1.0,2,1.859098,1.736502,0,100
3,0,1,1,1,12,1,33,62.669863,12.0,2,3.205633,3.357215,0,100
4,1,1,1,1,1,0,26,198.362265,1.0,3,1.113884,1.120078,0,200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,1,1,1,0,12,0,33,2.406023,12.0,8,2.284497,2.349070,0,200
3996,0,1,0,0,1,1,29,68.883764,1.0,1,1.277168,0.292859,1,100
3997,1,1,1,1,12,0,28,78.250542,11.0,2,2.786146,2.831439,0,200
3998,0,1,1,1,6,0,32,61.912657,5.0,3,1.630108,1.596237,0,100
3999,1,0,1,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0,200

### 3.5 Изменение содержимого ячейки

In [145]:
df.iloc[0, -1] = 0
df # меняем значение конкретной ячейки

,gender,Near_Location,Partner,Promo_friends,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn,Sum of Avgs
0,1,1,1,1,6,1,29,14.227470,5.0,3,0.020398,0.000000,0,0
1,0,1,0,0,12,1,31,113.202938,12.0,7,1.922936,1.910244,0,100
2,0,1,1,0,1,0,28,129.448479,1.0,2,1.859098,1.736502,0,100
3,0,1,1,1,12,1,33,62.669863,12.0,2,3.205633,3.357215,0,100
4,1,1,1,1,1,0,26,198.362265,1.0,3,1.113884,1.120078,0,200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,1,1,1,0,12,0,33,2.406023,12.0,8,2.284497,2.349070,0,200
3996,0,1,0,0,1,1,29,68.883764,1.0,1,1.277168,0.292859,1,100
3997,1,1,1,1,12,0,28,78.250542,11.0,2,2.786146,2.831439,0,200
3998,0,1,1,1,6,0,32,61.912657,5.0,3,1.630108,1.596237,0,100
3999,1,0,1,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0,200

In [147]:
df.iloc[0, -1] = 200
df

,gender,Near_Location,Partner,Promo_friends,Contract_period,Group_visits,Age,Avg_additional_charges_total,Month_to_end_contract,Lifetime,Avg_class_frequency_total,Avg_class_frequency_current_month,Churn,Sum of Avgs
0,1,1,1,1,6,1,29,14.227470,5.0,3,0.020398,0.000000,0,200
1,0,1,0,0,12,1,31,113.202938,12.0,7,1.922936,1.910244,0,100
2,0,1,1,0,1,0,28,129.448479,1.0,2,1.859098,1.736502,0,100
3,0,1,1,1,12,1,33,62.669863,12.0,2,3.205633,3.357215,0,100
4,1,1,1,1,1,0,26,198.362265,1.0,3,1.113884,1.120078,0,200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,1,1,1,0,12,0,33,2.406023,12.0,8,2.284497,2.349070,0,200
3996,0,1,0,0,1,1,29,68.883764,1.0,1,1.277168,0.292859,1,100
3997,1,1,1,1,12,0,28,78.250542,11.0,2,2.786146,2.831439,0,200
3998,0,1,1,1,6,0,32,61.912657,5.0,3,1.630108,1.596237,0,100
3999,1,0,1,0,12,1,30,178.861814,12.0,1,1.101832,1.035270,0,200

### 3.6 Создаём столбец на основе данных другого столбца

In [148]:
df["Churn Binary"] = df["Churn"].apply(lambda x: True if x==1 else False) # применяем лямбда-функцию

In [165]:
r = df.groupby("Age")["Churn"].mean()
r

Age
18    1.000000
19    0.500000
20    0.785714
21    0.791667
22    0.787879
23    0.682927
24    0.587838
25    0.562771
26    0.443333
27    0.367725
28    0.304251
29    0.254274
30    0.177243
31    0.129032
32    0.098901
33    0.067194
34    0.045977
35    0.030612
36    0.000000
37    0.000000
38    0.100000
39    0.000000
41    0.000000
Name: Churn, dtype: float64

# 4. Сохранение в других форматах и удаление

### 4.1 Вывод в CSV

In [166]:
df.to_csv("g.csv")

### 4.2 Вывод в JSON

In [167]:
df.to_json("j.csv")

### 4.3 Вывод в  HTML

In [168]:
df.to_html("h.html")

### 4.4 Удаление

In [171]:
del df